name: 'cluster_test'
on:
  workflow_dispatch:
    
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash
env:
  REGION: us-east-1
  ENV: dev
  
jobs:  
  cluster-test:
    name: 'cluster-test'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2       

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MM_NONPROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MM_SECRET_KEY_ID }}
        aws-region: ${{ env.REGION }}
         
    - name: klubeconfig update
      run: aws eks update-kubeconfig --region us-east-1 --name mm
      
    - name: kubectl get nodes
      run: kubectl get nodes
